keys: # ssh-to-age -i /etc/ssh/ssh_host_ed25519_key.pub
  - &nixos-xps age1ux7xcmxf77wjtnzcykcpm2h8pcnudf9c5e0ncudfd2qgvuwuq3pqmyj0xl
  - &nixos-gcp age1js0r7ap05js7t3ctjxmzt3q6l0rc4dz28xqrx2k468znt386efsq8ky25h
  - &nixos-macmini age1xkm04qn4r7gvd6a962t863gmzzpzeqqvusrdfq293uelktrc4v0qz2d6nk
  - &nixos-macbook age1q2tee5p4ffxu6g4g90gfcykcwttr9u5p4sqg4n494uelt2cqhefsleexuy
  - &nixos-nas age1aedtqphdcvyaz2vhxysy9xx5l47vckp8xy0fngmwgg36wmt3zftq7yjqkc 
  - &nixos-oci age1s9tauh069l9esyzwmudfkz7t226kkattp6qvze36p4950en3xqysduf4xg 
  - &nixos-testvm age1pjq3zvaug8mxzht4y50y3njyqlcmpa2g309zdmvz4ery996nxseq36uj3n
  - &nixos-chromebox age1mauey7sxlg8ty5ppea89wfztr7vu5nm7fc6k8g32rt3je7uy73wssed96c
  - &nixos-asus age10ha4nhq4aujqh3e76y8vntv6qcahgfq6lf49c0udplyme74uxy3swvjm7s
  - &nixos-g1a age13a2es7d6ufmfllmj5st3dup35v6sha2gtxf4ruutsf36f24gj96q5c4t4e
  - &recovery age14u76z7ch37cx6hesffvr3kazmjjyxhnsvja2xspznt8683xn79ksxg8f4r # just in case
creation_rules:
  - path_regex: ^secrets/common\.yaml$
    key_groups:
    - age:
      - *nixos-xps
      - *nixos-gcp
      - *nixos-macmini
      - *nixos-macbook
      - *nixos-nas
      - *nixos-oci
      - *nixos-testvm
      - *nixos-chromebox
      - *nixos-asus
      - *nixos-g1a
      - *recovery
  - path_regex: ^secrets/nixos-nas\.yaml$
    key_groups:
    - age:
      - *nixos-nas
      - *nixos-xps # dev
      - *nixos-macbook # dev
      - *nixos-asus # dev
      - *nixos-g1a # dev
      - *recovery
  - path_regex: ^secrets/nixos-macbook\.yaml$
    key_groups:
    - age:
      - *nixos-macbook
      - *nixos-xps # dev
      - *nixos-asus # dev
      - *nixos-g1a # dev
      - *recovery
  - path_regex: ^secrets/nixos-xps\.yaml$
    key_groups:
    - age:
      - *nixos-xps
      - *nixos-macbook # dev
      - *nixos-asus # dev
      - *nixos-g1a # dev
      - *recovery
  - path_regex: ^secrets/nixos-macmini\.yaml$
    key_groups:
    - age:
      - *nixos-macmini
      - *nixos-xps # dev
      - *nixos-macbook # dev
      - *nixos-asus # dev
      - *nixos-g1a # dev
      - *recovery
  - path_regex: ^secrets/nixos-gcp\.yaml$
    key_groups:
    - age:
      - *nixos-gcp
      - *nixos-xps # dev
      - *nixos-macbook # dev
      - *nixos-asus # dev
      - *nixos-g1a # dev
      - *recovery
  - path_regex: ^secrets/nixos-oci\.yaml$
    key_groups:
    - age:
      - *nixos-oci
      - *nixos-xps # dev
      - *nixos-macbook # dev
      - *nixos-asus # dev
      - *nixos-g1a # dev
      - *recovery
  - path_regex: ^secrets/nixos-asus\.yaml$
    key_groups:
    - age:
      - *nixos-asus
      - *nixos-xps # dev
      - *nixos-macbook # dev
      - *nixos-g1a # dev
      - *recovery
  - path_regex: ^secrets/nixos-g1a\.yaml$
    key_groups:
    - age:
      - *nixos-g1a
      - *nixos-xps # dev
      - *nixos-macbook # dev
      - *nixos-asus # dev
      - *recovery
  - path_regex: ^secrets/other\.yaml$
    key_groups:
    - age:
      - *nixos-xps # dev
      - *nixos-macbook # dev
      - *nixos-asus # dev
      - *nixos-g1a # dev
      - *recovery
