#!/bin/sh
set -xe

ZONE=us-central1-a
NAME=nixos-boost
VM=freetier

zpool remove nixos scsi-0Google_PersistentDisk_$NAME-part1
zpool remove nixos scsi-0Google_PersistentDisk_$NAME-part3

echo N > /sys/module/zswap/parameters/enabled
swapoff /dev/disk/by-id/google-$NAME-part2

gcloud compute instances detach-disk $VM --disk $NAME --zone $ZONE
gcloud compute disks delete $NAME --zone $ZONE --quiet

